// Ensure this is assigned to your database object
// If this is a separate file, use: examDatabase['PHY102'] = [...]
const PHY102 = [
    { q: "The two form of electricity are...?", o: ["Static and current", "Power and work", "Resistance and static", "Resistance and current"], a: 0 },
    { q: "The material gases has a charge carriers of.....?", o: ["Electrons", "Protons", "Electron and ions", "Proton and ions"], a: 2 },
    { q: "The addition of impurities to the conductivity and other properties of a semiconductor is called....?", o: ["Conductivity", "Malleability", "Doping", "Ductility"], a: 2 },
    { q: "The correct formula for the quantity of charge is...?", o: ["Q=VT", "Q= IT", "Q= I/T", "Q= VR"], a: 1 },
    { q: "The type of electric current delivered to businesses and residences is what...?", o: ["Alternating current", "Visual current", "Direct current", "General current"], a: 0 },
    { q: "Electric current is a derive quantity....?", o: ["True", "False", "True or false", "None of the above"], a: 1 },
    { q: "Factors that affect the resistance of a wire include all EXCEPT....?", o: ["Length", "Temperature", "Nature of Material", "Resistivity"], a: 3 },
    { q: "The usual waveform of an Alternating current is....?", o: ["Cosine wave", "Tan wave", "Sine wave", "Electrical wave"], a: 2 },
    { q: "Resistance of a material depends on the following EXCEPT....?", o: ["Length", "Resistivity", "Cross sectional area", "Temperature"], a: 3 },
    { q: "Potential difference is measured using...?", o: ["Henry", "Ammeter", "Farad", "Voltmeter"], a: 3 },
    { q: "Are devices for storing electrical charge which can then be released in a controlled manner whenever required.", o: ["Resistors", "Inductors", "Capacitors", "Ohms meter"], a: 2 },
    { q: "Capacitors is divided into two types called the Fixed and functional Capacitor...?", o: ["True", "False", "True and false", "All of the above"], a: 1 },
    { q: "Capacitors contain at least two conducting plates separated by insulating materials called what....?", o: ["Fixed capacitor", "Variable", "Functional", "Dielectrics"], a: 3 },
    { q: "The Dielectrics of super capacitor is....?", o: ["Polypropylene", "Helmholtz double layer", "Polyethylene sulfide", "Paper"], a: 1 },
    { q: "The Dielectrics of the film capacitors is....?", o: ["Paper", "Polyethylene sulfide", "Pare electric", "Aluminum oxide"], a: 1 },
    { q: "The factors affecting capacitance depend on the following EXCEPT...?", o: ["Distance between the plates", "Cross sectional area", "Temperature", "Dielectric"], a: 2 },
    { q: "The formula for the equivalent Resistor in series and the equivalent capacitor in series is same formula...?", o: ["False", "True", "True and False", "All of the above"], a: 0 },
    { q: "Two capacitors (0.30 microfarad and 0.50 microfarad) are connected in parallel. What is the equivalent capacitance...?", o: ["0.8 microfarad", "0.8 farad", "0.2 farad", "0.2 microfarad"], a: 0 },
    { q: "Capacitors can not be connected in parallel and series...?", o: ["True", "False", "True and False", "All of the above"], a: 0 },
    { q: "The important types of fixed capacitors are...?", o: ["Polymer capacitors", "Super capacitors", "Transit capacitors", "Silver mica"], a: 3 },
    { q: "What is the frequency of a wave, given that it's period is about 0.01667.", o: ["50.05Hz", "59.98Hz", "70.98Hz", "10Hz"], a: 1 },
    { q: "Gusts of wind make the Sears Building in Chicago sway back and forth at a vibration frequency of about 0.1Hz. what is the period of vibration?", o: ["20s", "30s", "40s", "10s"], a: 3 },
    { q: "If a water wave oscillates up and down three times each second and the distance between wave crest is 2m. What is it's wave speed?", o: ["6m/s", "8m/s", "10m/s", "12m/s"], a: 0 },
    { q: "Transformers works on the basis of Faraday's law?", o: ["True", "False", "Maybe", "None of the above"], a: 0 },
    { q: "Electrostatics is the study of:", o: ["Moving charges", "Stationary charges", "Magnetic fields", "Current electricity"], a: 1 },
    { q: "Electric charge is:", o: ["The flow of electrons", "A property of matter responsible for electrical effects", "The movement of protons", "Energy produced by magnets"], a: 1 },
    { q: "The law of conservation of electric charge states that:", o: ["Charge can be created", "Charge can be destroyed", "Total charge in an isolated system remains constant", "Electrons never move"], a: 2 },
    { q: "The two types of electric charges are:", o: ["North and South", "Positive and Neutral", "Positive and Negative", "Negative and Neutral"], a: 2 },
    { q: "Coulomb’s law states that the electrostatic force between two charges is:", o: ["Directly proportional to the square of the distance", "Inversely proportional to the square of the distance", "Independent of distance", "Directly proportional to mass"], a: 1 },
    { q: "Charging by friction occurs when:", o: ["Charges are created", "Two objects are rubbed together causing transfer of electrons", "Objects are heated", "Current flows in a wire"], a: 1 },
    { q: "Charging by conduction means:", o: ["Charging without contact", "Charging through radiation", "Charging by direct contact", "Charging by heating"], a: 2 },
    { q: "Charging by induction is:", o: ["Charging by direct contact", "Charging by rubbing", "Charging without physical contact", "Charging by heating"], a: 2 },
    { q: "One property of electric charges is that:", o: ["Unlike charges repel", "Like charges attract", "Like charges repel", "Charges have no effect"], a: 2 },
    { q: "An electric field is:", o: ["A magnetic region", "A region around a charge where force is experienced", "A conducting material", "A type of current"], a: 1 },
    { q: "Electric field intensity is defined as:", o: ["Force per unit charge", "Charge per unit force", "Energy per unit charge", "Voltage per unit current"], a: 0 },
    { q: "The SI unit of electric charge is:", o: ["Volt", "Coulomb", "Ampere", "Ohm"], a: 1 },
    { q: "The principle of quantization of charge states that charge exists in:", o: ["Fractions", "Continuous form", "Integral multiples of electronic charge", "Negative values only"], a: 2 },
    { q: "Conductors differ from insulators because conductors:", o: ["Do not allow charge movement", "Allow free movement of electrons", "Have no electrons", "Are always positively charged"], a: 1 },
    { q: "Which of the following is an application of electrostatics?", o: ["Electric iron", "Photocopier", "Water heater", "Refrigerator"], a: 1 },
    { q: "A conductor is a material that:", o: ["Prevents movement of charges", "Allows free flow of electric charges", "Has no electrons", "Cannot be charged"], a: 1 },
    { q: "An insulator is a material that:", o: ["Allows free movement of charges", "Conducts heat only", "Resists the flow of electric charges", "Produces electricity"], a: 2 },
    { q: "The formula for Coulomb’s law is:", o: ["F=ma", "V=Ir", "F=kq1q2/r²", "P=Iv"], a: 2 },
    { q: "The magnitude of electric field E at a point 2.0 m from a charge of 4.0nc is calculated using:", o: ["9.0N/C", "18N/C", "27N/C", "36N/C"], a: 0 },
    { q: "The number of electrons removed from a coin to leave a charge of +1.0×10–⁷C is approximately:", o: ["6.25×10¹¹", "6.25×10¹²", "1.60×10–¹⁹", "3.20×10–⁷"], a: 1 },
    { q: "The magnitude of electrostatic force between Na+ and Cl– ions separated by 2.82×10–¹⁰ is calculated using:", o: ["2.9×10–⁹", "8.2×10–⁹", "1.6×10–¹⁹", "9.0×10¹⁹"], a: 1 },
    { q: "A crack in the magnetic path of an inductor will result in ____", o: ["unchanged inductance", "Increased inductance", "Zero inductance", "Reduced inductance"], a: 3 },
    { q: "A coil is wound on iron core which carries current I. The self induced voltage in the coil is not affected by ____", o: ["Variation in coil current", "Variation in voltage of the coil", "Change of number of turns of coil", "The resistance of magnetic path"], a: 3 },
    { q: "A moving magnetic field will produce the same effect as a conductor that is moving", o: ["Yes", "No", "a and b", "All of the above"], a: 3 },
    { q: "The polarity of the induced voltage can be determined by using the left hand generator rule.", o: ["Yes", "No", "All of the above", "None of the above"], a: 0 },
    { q: "Increasing the field or increasing the current will decrease the force on the conductor", o: ["Yes", "No", "All of the above", "None of the above"], a: 1 },
    { q: "Reversing the field or the current will reverse the force on the conductor", o: ["Yes", "No", "All of the above", "None of the above"], a: 0 },
    { q: "If the current in one coil becomes steady, the current in neighbouring coil is ___", o: ["Zero", "Infinity", "Double", "Halves"], a: 0 },
    { q: "If the flux linkage in coil 1 is 3Wb and it has 500 turns and the current in coil 2 is 2A, calculate the mutual inductance.", o: ["750H", "500H", "450H", "900H"], a: 0 },
    { q: "When a conductor moves in the field, so that it makes an angle 8 with the line of flux, the force F is given as: F = Blsin20°", o: ["Yes", "No", "All of the above", "None of the above"], a: 1 },
    { q: "The self inductance of the coil may be defined as equal to the e.m.f induced in volts when the current in the circuit changes at the rate of unit Weber turns", o: ["Yes", "No", "All of the above", "None of the above"], a: 0 },
    { q: "The flux linkage in coil 1 is 3Wb and it has x turns and the current in coil 2 is 2A, calculate the value of x if the mutual inductance is 750H.", o: ["300", "400", "500", "700"], a: 2 },
    { q: "The flux linkage in coil 1 is x and it has 500 turns and the current in coil 2 is 2A, calculate the value of x if the mutual inductance is 759H", o: ["1Wb", "2Wb", "3Wb", "4Wb"], a: 2 },
    { q: "Practical application of mutual inductance is _____", o: ["DC generator", "AC generator", "Transformer", "Capacitor"], a: 2 },
    { q: "The phenomenon die to which there is an induced current in one coil due to the current in a neighbouring coil is ___", o: ["Electromagnetism", "Susceptance", "Mutual Inductance", "Steady current"], a: 2 },
    { q: "If the current in one coil is steady, what happens to the mutual Inductance?", o: ["Zero", "Infinity", "Double", "Halves"], a: 0 },
    { q: "What is the SI unit of mutual inductance?", o: ["Ohm", "Henry", "Volt", "Siemens"], a: 1 },
    { q: "The flux linkage in coil 1 is 3Wb and it has 500 turns and tye current in coil 2 is xA, calculate the value x if the mutual inductance is 750H.", o: ["1A", "2A", "3A", "4A"], a: 1 },
    { q: "The inductor does not allow sudden changes in ____", o: ["Voltage", "Current", "Inductance", "Capacitance"], a: 1 },
    { q: "The electrical energy consumed by a coil is stored in the form of ____", o: ["An electrical field", "A magnetic Field", "An Electrostatic Field", "A force field"], a: 1 }
];

// Combine this with your existing database
if (typeof examDatabase !== 'undefined') {
    examDatabase['PHY102'] = PHY102;
                                                                  }
  
